keypath: "id_rsa"

port: "2042"

version: "SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.11"

users:
  alice: "motdepasse1"
  bob: "motdepasse2"
  charlie: "motdepasse3"

nopassdump:
  - "thiecail"
  - "nicocour"
  - "sabigalu"
  - "rolatouc"

hosts:
   "192.168.78.99" : "greenbone.si"
